# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
sudo: false
cache: packages
r:
  - oldrel
  - release
  - devel  
before_install:
  - tlmgr install index
addons:
  apt:
    packages:   
    - libnlopt-dev
    - libxml2-dev
    - libv8-dev
warnings_are_errors: false
