language: r
sudo: false
cache: packages
r:
  - oldrel
  - release
  - devel  
before_install:
  - tlmgr install index
repos:
  CRAN: http://cran.rstudio.com
addons:
  apt:
    packages:
      - libxml2-dev
      - libv8-dev
warnings_are_errors: false