language: r
sudo: required
dist: trusty
group: deprecated-2017Q4
cache: packages
r:
  - oldrel
  - release
  - devel
before_install:
  - tlmgr install index
warnings_are_errors: false
install: travis_wait mvn install
