language: r
sudo: false
cache: packages
r:
  - oldrel
  - release
  - devel
## Use patched devtools
r_github_packages:
  - hadley/devtools
before_install:
  - tlmgr install index
addons:
  apt:
    packages:
    - libnlopt-dev
warnings_are_errors: false
